### ISSUE TITLE
Error on `dfm init [profile]`

### ISSUE THREAD

**Issue by davidmyersdev** [chasinglogic/dfm#23]
## Version:

Output of `dfm -v`.

```
dfm version 1.0-dev
```

## Command:

```bash
dfm init [profile]
```

## Error:

```
mkdir /Users/[user]/.config/dfm/profiles/[profile]: no such file or directory
```

## Steps to Reproduce:

Make sure your `/Users/[user]/.config/dfm` directory doesn't exist yet, and then try to `dfm init` a new profile.

### Option 1:

Use `os.MkdirAll` instead of `os.Mkdir` in `init.go` on [line 20](https://github.com/chasinglogic/dfm/blob/9b0be36e3a6be1f4befd110ce9b4945127a85538/init.go#L20).

### Option 2:

Add check to make sure `dfm` directory exists in [`getProfileDir()`](https://github.com/chasinglogic/dfm/blob/9b0be36e3a6be1f4befd110ce9b4945127a85538/config.go#L66) or [`LoadConfig()`](https://github.com/chasinglogic/dfm/blob/9b0be36e3a6be1f4befd110ce9b4945127a85538/config.go#L22).

**Comment by chasinglogic** [comment]
Thanks for the amazing bug report! I added the fix and pushed to master so you can pull it down.

**Comment by davidmyersdev** [comment]
Thanks for the quick response. I'll check it out as soon as I get a chance and get back with you.
