### ISSUE TITLE
issue might be I am an idiot

### ISSUE THREAD

**Issue by XakV** [chasinglogic/dfm#25]
I tried to follow the starting with a blank repo instructions. First, I forgot my github password. I usually use ssh. I have a password on my ssh key, no big deal. I added bash as an ssh agent, ran ssh-add, but now dfm would not allow me to add the remote. I thought to myself, "dude, you watched this guy's git talk, you got this," and dove down into my meager git skills. cd'ing into the profile i had added for dfm, i was able to run git remote add origin, and I am in business! Well, sort of. Because I created the new dotfile repo, I had to pull down the readme. I ran into a merge conflict message I had to google, and then added --allow-unrelated-histories to my git pull command. Then finally, dfm push worked as expected.

I have to say, I have tried yadm as well (another dotfiles manager) and couldnt get my head around the concept enough to say I liked using it. I like the concept you have here, it makes more sense to me, but I don't know if the README section needs some caveats for "advanced idiots" like myself, or if I'm just really bad at git in general.

I wont be upset if you just close out this issue with a note that says "user is way too dumb", but if there is something I can add to the readme, or maybe improve some error message, I will be happy to do that and send a pull request. I dont know golang, but how hard can it be for an intelligent chap like myself? :)

If it helps you to suss out what I did wrong, here is a bit of my history, note I skipped to the last, semi-successful attempt;

  174  dfm add .dir_colors
  175  dfm add .Xresources
  176  dfm add .taskrc .tmux.conf .vimrc .kshrc
  177  dfm commit -am "init again?"
  178  dfm remote _#tried to get dfm to tell me what the remote was_
  179  dfm remote git@github.com:AffableZonkey/differntdots.git
  180  dfm remote add spatterjay git@github.com:AffableZonkey/differntdots.git
  181  dfm remote add git@github.com:AffableZonkey/differntdots.git
  184  cd spatterjay/
  186  git remote
  187  git remote add origin git@github.com:AffableZonkey/differntdots.git
  188  dfm push
  189  dfm pull
  190  git checkout master
  192  git branch -l
  193  git pull
  194  git pull --set-upstream-to=origin/spatterjay master
  196  git branch -l
  197  dfm pull
  198  git merge
  199  git remote add master git@github.com:AffableZonkey/differntdots.git
  206  git branch --set-upstream-to=origin/master origin
  207  git pull origin master
  208  git pull origin master --allow-unrelated-histories
  209  dfm push

**Comment by chasinglogic** [comment]
Actually turns out I'm the idiot. I never wrote the remote command! I'll get on that right now thanks for the bug report!

**Comment by chasinglogic** [comment]
@AffableZonkey I pushed a fix and updated the documentation in the README if you wouldn't mind checking it that would be awesome! If you notice anything feel free to fork it and submit your changes or just open a new issue. Thanks again for the bug report!

**Comment by XakV** [comment]
Hey thanks Matt! I will try it out shortly.
