### ISSUE TITLE
dfm init profile-name does not create dfm/profiles directory.

### ISSUE THREAD

**Issue by cbusenbu** [chasinglogic/dfm#32]
I was using dfm init to initialize my profile from scratch, and it creates a dfm folder in .config, but does not create a profiles folder if it doesn't exist yet. Once it does exist everything runs fine.

**Comment by chasinglogic** [comment]
I've pushed a fix and updated the version on PyPi if you update using `pip3 install --upgrade dfm` you should be good to go! Thanks
