### ISSUE TITLE
dfm add does not check if file is already linked.

### ISSUE THREAD

**Issue by cbusenbu** [chasinglogic/dfm#34]
dfm add doesn't check if file is already symbolically linked, thus can lead to following error. if dfm add ran multiple times

-bash: cd: .emacs.d: Too many levels of symbolic links

**Comment by chasinglogic** [comment]
dfm add now refuses to link symlinks and also attempt to work on files that don't exist.

I've uploaded version 2.2.2 with various bug fixes including this one to PyPi
