### ISSUE TITLE
.gitignore not ignored by dfm

### ISSUE THREAD

**Issue by jedrw** [chasinglogic/dfm#67]
My understanding is that dfm should ignore `.gitignore` files by default but is not doing so for me.

```
┌─(kube: tk3s)
└─[jedrw@qvostro ~]$ rm ~/.gitignore
┌─(kube: tk3s)
└─[jedrw@qvostro ~]$ dfm link
┌─(kube: tk3s)
└─[jedrw@qvostro ~]$ ls -la .gitignore
lrwxrwxrwx 1 jedrw jedrw 52 Oct 20 16:16 .gitignore -> /home/jedrw/.config/dfm/profiles/dotfiles/.gitignore
```

**Comment by chasinglogic** [comment]
Can you post your `.dfm.yml`?

**Comment by chasinglogic** [comment]
Nevermind, I found the bug and found another way in which this didn't work as documented. I'm fixing it now.

**Comment by chasinglogic** [comment]
10.3.2 has been released that includes this fix
